### ISSUE TITLE
[FEATURE] DSL for Opensearch PHP

### ISSUE THREAD

**Issue by shyim** [opensearch-project/opensearch-clients#26]
Hey,

I [forked](https://github.com/shyim/opensearch-dsl) a very popular [Elasticsearch DSL library for PHP](https://github.com/ongr-io/ElasticsearchDSL) and would maintain it. 

I would just ask here if this is maybe interesting for the opensearch-project org? 

I renamed already it to Open search and upgraded the code for the new apis

**Comment by dblock** [comment]
Is this different from https://github.com/opensearch-project/opensearch-dsl-py?

**Comment by shyim** [comment]
Its similar, but for PHP

**Comment by brijos** [comment]
Quick update, I'm going to start the process of creating a new repo for this. I'll keep this thread updated as we progress.

**Comment by shyim** [comment]
I talked with Beckler, Bill and we leave it still in my account and link to here
