### ISSUE TITLE
[FEATURE] Introduce Spring Data Opensearch

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-clients#28]
**Is your feature request related to a problem? Please describe.**

Taking into account how widely popular Spring Data Elasticsearch is, it is highly likely that community would seek the first class support of the OpenSearch integration. In scope of this issue and multiple discussions with Spring Data Elasticsearch team (@sothawo), the decision has been made to host the integration on OpenSearch side as a standalone project based on Spring Data Elasticsearch 5.0, under `spring-data-opensearch` repository.

The existing pull request [3] will become the foundation for  `spring-data-opensearch` integration, with minor changes required on Spring Data Elasticsearch as well.

**Describe the solution you'd like**
Create new repository `spring-data-opensearch` to host Spring Data Opensearch project

**Describe alternatives you've considered**
The option to bundle Spring Data Elasticsearch with OpenSearch is feasible but pose a significant maintenance overhead, the agreement was reached to have it as a separate deliverables (under OpenSearch project). 

**Additional context**

[1] https://github.com/spring-projects/spring-data-elasticsearch/issues/1770
[2] https://github.com/spring-projects/spring-data-elasticsearch/issues/1918
[3] https://github.com/spring-projects/spring-data-elasticsearch/pull/2203

**Comment by dblock** [comment]
I moved this to opensearch-clients, I think it's a better home for it.

**Comment by brijos** [comment]
Any concerns naming it opensearch-spring-data instead? That would match our current naming convention for clients better.

**Comment by reta** [comment]
> Any concerns naming the repo opensearch-spring-data instead? That would match our current naming convention for clients better.

I would personally think `spring-data-opensearch` is something people will have no difficulties to find (inspiration from `spring-data-opensearch`)

**Comment by rursprung** [comment]
the spring naming convention is clearly `spring-[..]` and anything spring data related is `spring-data-[..]` (e.g. `spring-data-elasticsearch`, `spring-data-jdbc`, etc. - see the [spring data overview](https://spring.io/projects/spring-data)).

**Comment by wbeckler** [comment]
Out of 15 community clients, 10 follow that convention and 5 follow other conventions.

**Comment by rursprung** [comment]
is there any update on this? i don't see a {{spring-data-opensearch}} (or similarly named) repository under either opensearch-project or spring-projects (where would the repo be hosted, anyway?). what are the next steps here / who's involved in them? at this point spring-data-elasticsearch based projects are still stuck and cannot move to OpenSearch 2.x.



> Out of 15 community clients, 10 follow that convention and 5 follow other conventions.

@wbeckler: that's still a clear pattern to me :) i'd strongly vote to go with {{spring-data-opensearch}} to be aligned with the majority (and the de-facto standard; it's also the only pattern you'll [find in the official spring-projects repositories](https://github.com/orgs/spring-projects/repositories?language=&q=data&sort=&type=all)).

**Comment by reta** [comment]
@rursprung we are waiting for repository to be created under OpenSearch organization (it is very long process right now) ...

**Comment by rursprung** [comment]
@reta thanks for letting me know! is this even the right place to host it? shouldn't it maybe be under the spring-projects umbrella? is there an ETA for this? and could development work potentially start elsewhere for the time being until the other repo is ready (the content can then either be force-pushed over whatever is in the new repo or merged with a "keep only ours" merge strategy; you'd just have to make sure to then re-apply any files which are required/mandated by the opensearch org if these can't be added directly to the quick-start repository)

**Comment by reta** [comment]
> is this even the right place to host it? shouldn't it maybe be under the spring-projects umbrella? is there an ETA for this?

Yes, we have mutual agreement with Spring team to proceed this way (the description highlights that)

> is there an ETA for this? 

We have done large chunk of work already but I do not have insights in repository ETA (hopefully soon), @brijos do you have updates may be?

> and could development work potentially start elsewhere for the time being until the other repo is ready 

https://github.com/spring-projects/spring-data-elasticsearch/pull/2203 is what we have now

**Comment by GabrielBB** [comment]
1 - Is this something that can be expected in 2022 ?
2 - Will this be for Spring Boot `>3.x` only or will it work with Spring Boot `2.7.x` ?

**Comment by sothawo** [comment]
You are asking at the wrong place. This is an OpenSearch issue and not Spring Data Elasticsearch anymore.

**Comment by reta** [comment]
@GabrielBB yes, we target Spring Data 5 release train and match its Spring Boot support line.
