### ISSUE TITLE
[FEATURE] Expand integration tests to Amazon OpenSearch for SigV4 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-clients#31]
**Is your feature request related to a problem?**

We have added SigV4 signing in various clients via #22. We don't have a way to run integration tests against the actual service.
 
**What solution would you like?**

A repeatable way to run Sigv4 signing tests for all clients.

**Do you have any additional context?**

See https://github.com/acm19/aws-request-signing-apache-interceptor/issues/40 for a similar ask.

**Comment by VachaShah** [comment]
Tracking this in #47
