### ISSUE TITLE
[META] Introduce keep-a-changelog to all clients

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-clients#33]
**What kind of business use case are you trying to solve? What are your requirements?**

Release notes are of varying quality. Similar to https://github.com/opensearch-project/OpenSearch/issues/1868. 

**What is the problem? What is preventing you from meeting the requirements?**

- Release notes aren't always super useful and may lack context.
- Release notes are only available at release time, and not during development, so it's unclear what has changed.

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**

1. Replace authoring release notes at the end before a release with authoring release notes in each PR.
2. Require that release notes be updated via something like [danger-changelog](https://github.com/dblock/danger-changelog) with every change.

An implementation of this was done in OpenSearch core in https://github.com/opensearch-project/OpenSearch/pull/4085. Copy-paste that into all clients.

**Comment by wbeckler** [comment]
How has this been going for core? If it's hunky dory, it makes sense to raise the bar for client repos.

**Comment by dblock** [comment]
> opensearch-project/OpenSearch#1868

Yep, like so: https://github.com/opensearch-project/OpenSearch/issues/1868

**Comment by dblock** [comment]
Here's another example why we should do this: https://github.com/opensearch-project/opensearch-js/issues/290#issuecomment-1275676617 - user is reading docs that are newer than the released software and I can't tell what was released in the last version vs. what was added since

**Comment by harshavamsi** [comment]
This is complete across all clients and can be closed. I'm tracking the discussion in https://github.com/opensearch-project/OpenSearch/issues/4936 and will update the implementation if anything changes.

**Comment by dblock** [comment]
I noticed we don't do CHANGELOG updates in some dependabot PRs, can we please fix that?

**Comment by harshavamsi** [comment]
> I noticed we don't do CHANGELOG updates in some dependabot PRs, can we please fix that?

It's weird. We have the [dependabot_pr action](https://github.com/opensearch-project/opensearch-js/blob/main/.github/workflows/dependabot_pr.yml) that should update the changelog if the PR is raised by dependabot. But sometimes we have to manually do a dependabot recreate to get it to update the changelog.

**Comment by dblock** [comment]
https://github.com/opensearch-project/opensearch-dsl-py/blob/main/CHANGELOG.md
https://github.com/opensearch-project/opensearch-go/blob/main/CHANGELOG.md
https://github.com/opensearch-project/opensearch-java/blob/main/CHANGELOG.md
https://github.com/opensearch-project/opensearch-js/blob/main/CHANGELOG.md
https://github.com/opensearch-project/opensearch-net/blob/main/CHANGELOG.md
https://github.com/opensearch-project/opensearch-php/blob/main/CHANGELOG.md
https://github.com/opensearch-project/opensearch-py/blob/main/CHANGELOG.md
https://github.com/opensearch-project/opensearch-ruby/blob/main/CHANGELOG.md
https://github.com/opensearch-project/opensearch-rs/blob/main/CHANGELOG.md
https://github.com/opensearch-project/opensearch-hadoop/blob/main/CHANGELOG.md
