### ISSUE TITLE
[FEATURE] Add Hacktoberfest to all repositories

### ISSUE THREAD

**Issue by shyim** [opensearch-project/opensearch-clients#37]
### Is your feature request related to a problem?

[Hacktober](https://hacktoberfest.com) fest started. It would be nice when all opensearch repositories have this tag too. to get contributions here

**Comment by dblock** [comment]
I've created labels in all repos in the org and PRed a doc on how to do that: https://github.com/opensearch-project/project-meta/pull/60, cc: @jdbright.
