### ISSUE TITLE
[FEATURE] Update MAINTAINERS

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/opensearch-clients#46]
This repo has three maintainers listed in the Maintainers.MD file:

| Maintainer               | GitHub ID                               | Affiliation |
| ------------------------ | --------------------------------------- | ----------- |
| Jack Mazanec             | [jmazanec15](https://github.com/jmazanec15) | Amazon |
| Vamshi Vijay Nakkirtha   | [vamshin](https://github.com/vamshin)   |   Amazon    |
| Vijayan Balasubramanian  | [VijayanB](https://github.com/VijayanB) |   Amazon    |

I propose we modify this list to include only the people who would potentially qualify as maintainers under the maintainers process, as mentioned in the maintainers.MD file or in the policy to which it links.

That would include only those developers listed here: https://github.com/opensearch-project/opensearch-clients/graphs/contributors

After that change I would, as an Admin in the Opensearch Project repositories, align the github maintainership permissions with that list.

**Comment by dblock** [comment]
@wbeckler I think since you manage a team at Amazon that works on clients I would vote to include you.

**Comment by wbeckler** [comment]
That makes sense. Does anyone else have thoughts?

**Comment by dblock** [comment]
This is part of #51

**Comment by VachaShah** [comment]
Closing as #51 is done.
