### ISSUE TITLE
Remove mapping type support 

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-clients#6]
**Is your feature request related to a problem?**
As part of v2.0 release, mapping type are removed from OpenSearch engine. Need to remove the support of type from clients
Issue [1940](https://github.com/opensearch-project/opensearch/issues/1940)

**What solution would you like?**
Upgrade the client code to remove usage of 
- Type API end-points
- Remove include_type_name parameter from API requests.

Top level changes are captured in gist below: 
https://gist.github.com/dreamer-89/d76eaf639171e8ab32fa7f8b9d6c93d3

For more detailed changes, please check meta issue below:
Related: [OpenSearch-engine meta issue](https://github.com/opensearch-project/opensearch/issues/1940)

**Comment by dreamer-89** [comment]
This change goes in `v2.0.0` release in OpenSearch repository and is a `breaking` change. Request maintainer to add appropriate labels.

**Comment by VachaShah** [comment]
Added as part of meta issue #12
