### ISSUE TITLE
[PROPOSAL] Lower number of PR approvers to 1

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-clients#73]
### What are you proposing?

This repo is a meta non-production repo, we don't need 2 approvers for all PRs.

### What problems are you trying to solve?

PRs sit too long, too few maintainers.

**Comment by dblock** [comment]
@harshavamsi @VachaShah need your +-1 please?

**Comment by VachaShah** [comment]
+1

**Comment by harshavamsi** [comment]
+1

**Comment by dblock** [comment]
I've reduced the number of approvers to 1, thank you!

<img width="767" alt="Screenshot 2024-09-03 at 2 58 06 PM" src="https://github.com/user-attachments/assets/b599ea76-1b51-4d4c-8a83-61f8e92a79cf">
